random_seed: 42
data:
  coco_dir: "data/coco"
  annotations_dir: "data/densepose"
  eval_data: "data/densepose/eval_data"
modules:
  models: ["model"]
  optims: ["optim"]
val_freq_epochs: 1
#val_freq_iters: 10
val_iou_types: ['uv', 'segm', 'bbox']
#val_iou_types: ['segm']
checkpoint:
  freq_iters: 1000

max_num_epochs: 10000

hp:
  dp_head_output_size: 50
  loss_coefs:
    dp_cls_loss: 0.3
    dp_u_loss: 0.1
    dp_v_loss: 0.1
    dp_mask_loss: 2.0
  grad_accum: 12

  optim:
    lr: 0.02
    momentum: 0.9
    weight_decay: 0.0001

  grad_clip_norm_value: 100
  batch_size: 2
  model_config:
    min_size: 800
    max_size: 1333
