title: "Playing with Mask RCNN"
trainer: "MaskRCNNTrainer"
random_seed: 42
coco_data_dir: "/home/skorokhodov/densepose/coco"
available_gpus: [8]
modules:
  models: ["model"]
  optims: ["optim"]

checkpoint:
  freq_iters: 1000

hp:
  optim:
    lr: 0.02
    momentum: 0.9
    weight_decay: 0.0001
  grad_clip_norm_value: 35
  batch_size: 2
  model_config:
    min_size: 800
    max_size: 1333
